command: ['npm', 'run', 'start']
env:
  - name: LAKEBASE_ENDPOINT
    valueFrom: postgres
  - name: DATABRICKS_VOLUME_FILES
    valueFrom: files
  - name: DATABRICKS_JOB_ID
    valueFrom: job
  - name: CONFIG_ADMIN_PRINCIPALS
    value: ${var.config_admin_principals}
  - name: CONFIG_DESTINATION_ALLOWLIST
    value: ${var.config_destination_allowlist}
